---
engine_version: 0.4.20
file_version: 2024-09-06 22:37:30.705637000 Z
resources:
- name: deal
  preferences:
    columns:
    - column_type: string
      virtual: true
      format: {}
      validators: []
      display_name: status
      default_value: 
      name: status
  updated_at: 2024-09-06 19:37:30.705637000 -03:00
- name: user
  preferences:
    columns:
    - access_type: hidden
      name: notifications
    - name: webpush_notify_on_event_expired
      display_name: webpush_notify_on_event_expired
      column_type: boolean
      access_type: read_write
      virtual: true
      format: {}
      validators: []
  updated_at: 2024-07-31 09:31:23.886169000 -03:00
configs:
- key: header.links
  value:
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  updated_at: 2024-09-06 15:21:42.306308000 -03:00
- key: resources.deal.columns.order
  value:
  - id
  - account_id
  - contact_id
  - stage_id
  - pipeline_id
  - name
  - status
  - custom_attributes
  - position
  - updated_at
  - created_at
  - status
  updated_at: 2024-09-06 19:35:25.310086000 -03:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description: 
  updated_at: 2024-09-06 15:21:42.341974000 -03:00
